# Generated by Django 5.0.2 on 2024-05-17 08:49

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Список пользователей'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backend.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время заказа'),
        ),
    ]
