# Generated by Django 5.0.2 on 2024-05-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Статус получения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reg_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время заказа'),
        ),
    ]
