# Generated by Django 5.0.6 on 2024-07-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10, verbose_name='Серия карты')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер карты')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска карты')),
                ('expiry_date', models.DateTimeField(verbose_name='Дата истичения срока карты')),
                ('status', models.CharField(choices=[('not activated', 'Не активирована'), ('activated', 'Активирована'), ('expired', 'Просрочена')], default='активирована', max_length=20)),
            ],
            options={
                'verbose_name': 'Дисконтная карта',
                'verbose_name_plural': 'Список дисконтных карт',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата использованиня карты')),
                ('description', models.TextField()),
                ('loyalty_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.loyaltycard')),
            ],
            options={
                'verbose_name': 'Транзакция карты',
                'verbose_name_plural': 'Список транзакций карт',
            },
        ),
    ]
