# Generated by Django 5.0.2 on 2024-06-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer', models.CharField(max_length=80, verbose_name='Клиент')),
                ('item', models.CharField(max_length=50, verbose_name='Камень')),
                ('total', models.PositiveIntegerField(verbose_name='Сумма')),
                ('quantity', models.IntegerField(verbose_name='Заказы')),
                ('date', models.DateTimeField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'История транзакций',
                'verbose_name_plural': 'Список истории транзакций',
            },
        ),
    ]
