version: '3.9'
# Общая сеть для всех контейнеров
networks:
  service_network:
services:
  # Образ и версия базы, которую мы будем использовать
  db:
    image: postgres:latest
    networks:
      service_network:
    # Перезапускаем все остановленные и работающие службы
    restart: always
    container_name: postgres
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    # Учетные данные
    env_file:
      - ./.env
      # Открываем порт 5432 внутри и снаружи
    ports:
      - "5432-5432"

volumes:
  postgres_volume: